In [46]:
import pandas as pd
import numpy as np

## Series

In [26]:
import numpy as np


# normal declaration
ser = pd.Series([1,2,3,4,5])
print(ser, type(ser))

# numpy arrays declartion
arr2 = np.array([1,2,3,4,5,6])  # numpy arrays creation

ser2 = pd.Series(arr2)  # conversion of numpy  arrays to series
ser3 = pd.Series(arr2 , index=["a","b","c","d","e","f"] )   # adding labels with appropriate indexes here index use d for lebeling the element based on retrival

print(ser2, type(ser2))
print(ser3, type(ser3))
print(ser3["c"], type(ser3))

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64 <class 'pandas.Series'>
a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64 <class 'pandas.Series'>
3 <class 'pandas.Series'>

In [ ]:
# homogenius
# handle missing values with NaN
# Vectorized opeeration + - * ...
# mutable values, immutable size

In [56]:
# fro different values the data type are object type otherwise homogeneus like group if int, group of char 
ser = pd.Series([1,2,3,"er",None, 's'])
ser = pd.Series([1,2,3,])
print(ser)

# vectorized operation

s1 = pd.Series([1,2,3])
s2 = pd.Series([4,5,6])


print(s1+s2)


# immutable size
s1=pd.Series([1,2,3])
s2 = s1.drop(1)
print(s1) 
print(s2)

0    1
1    2
2    3
dtype: int64
0    5
1    7
2    9
dtype: int64
0    1
1    2
2    3
dtype: int64
0    1
2    3
dtype: int64

## Data Frame

In [63]:
# simple  creation
import pandas as pd  
data  = {
    "soumya" : [1,2,3],
    "ritesh" : [3,2,1],
    "rahul" : [3,4,2]
}
df = pd.DataFrame(data, index = ["1st Score" , "2nd Score","3rd Score"]) # WITH PARAMETER INDEX VALUES
print(df)


# USING LIST
df = pd.DataFrame([[1,2,3],[4,5,6]])
print(df, type(df))
df
# OR WE CAN CREATE 2D ARRAY AS NUMPY AND ASIIGN AT THEN PARAMETER IN THE DATAFRAME

           soumya  ritesh  rahul
1st Score       1       3      3
2nd Score       2       2      4
3rd Score       3       1      2
   0  1  2
0  1  2  3
1  4  5  6 <class 'pandas.DataFrame'>

   0  1  2
0  1  2  3
1  4  5  6

### Data reading from csv and json

In [79]:
import pandas as pd
data = pd.read_csv("data\example.csv")
print(data)
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

<>:2: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Asus\AppData\Local\Temp\ipykernel_2416\3979877914.py:2: SyntaxWarning: invalid escape sequence '\e'
  data = pd.read_csv("data\example.csv")

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [92]:
import pandas as pd
data = pd.read_json("data\exp.json")
print(data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

<>:2: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Asus\AppData\Local\Temp\ipykernel_2416\87233.py:2: SyntaxWarning: invalid escape sequence '\e'
  data = pd.read_json("data\exp.json")

In [44]:
print(data.shape)
# data.head(3)
# data.tail(7)
# data.sample()
# data.info()
data.describe()
# # data.columns
# # data.nunique()

(9721, 15)

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000,9721.000000
mean,23.067194,36.803569,47.617465,74.598578,37.489296,6.022434,48.181314,0.799755,123.256352,21.556557,57.769082,5.277969
std,26.148928,78.267681,18.311530,27.328815,14.415390,2.471385,14.927705,0.249523,17.824975,9.526050,18.835319,2.729117
min,-37.814000,-123.121000,0.029000,0.061000,0.013000,0.003000,0.114000,0.017000,101.000000,5.001000,25.002000,0.500000
25%,12.972000,2.352000,34.750000,55.347000,27.194000,4.342000,38.075000,0.633000,109.000000,13.345000,41.274000,2.937000
50%,28.704000,37.617000,51.334000,73.718000,40.504000,6.003000,48.391000,0.802000,119.000000,21.470000,58.053000,5.290000
75%,41.008000,103.820000,60.121000,94.814000,47.641000,7.697000,58.468000,0.967000,133.000000,29.820000,74.238000,7.645000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.721000,231.000000,37.998000,89.994000,9.999000

### Data set from kaggle

In [125]:
import pandas as pd
df =  pd.read_csv("data\globalAirQuality.csv")
df.head()
df.tail()
# df.info()
df.columns
df.nunique()
# df["city"] is same as df.city
df[["city","aqi"]]

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Asus\AppData\Local\Temp\ipykernel_3212\3407813284.py:2: SyntaxWarning: invalid escape sequence '\g'
  df =  pd.read_csv("data\globalAirQuality.csv")

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [134]:
# data selection
df["city"]
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [137]:
# row selection
# iloc --- for accesng by index values 
# loc --- for acessiing by label based values

df.loc[0]  #----  for acessing by label values
df.loc[0:2]  # end index inclusive (included)
df.iloc[2]  #----  for acessing througn index values
df.iloc[0:3] # end index exclusive   (not included)

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [126]:
# selecting row and columns both 
# we use loc
df.loc[0,["aqi","city"]]
df.loc[0:3,["aqi","city"]]

# df.iloc[0:3,["aqi","city"]]     ---- .iloc requires numeric indexers, got ['aqi' 'city'] ------ it takes numeric vlaues only   incase of string it fails bca it doesnot takes string
df.iloc[0:2,[11,2]]   # --- we actually use the index vales of columns
# df.info()    --- helps for figuring out the indexes of columns
# 
df.iloc[0:2,1:5]   #----- using slicing   --- end index is excluded

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [127]:
# for a acessing single scaler vaues
# CELL
# at(lebel) and iat(index)

df.at[0,"city"]
df.iat[0,4]

np.float64(-74.006)

When selecting data in Pandas, sometimes Pandas creates a copy of data and sometimes a view of original data.
This creates confusion called SettingWithCopy conflict.

Simple Explanation
View → changes affect original data
Copy → changes do NOT affect original data

Scalar value means selecting single value from DataFrame.

SettingWithCopyWarning

In [161]:
import pandas as pd

df = pd.DataFrame({
    "marks": [80, 90, 70]
})

new_df = df[df["marks"] > 75]

new_df["marks"] = 100

print(new_df)
print(df)

   marks
0    100
1    100
   marks
0     80
1     90
2     70

In [ ]:

import pandas as pd

df = pd.DataFrame({
    "marks": [80, 90, 70]
})

new_df = df[df["marks"] > 75].copy() # we use copy for the data for mistakely change the values in original data

new_df["marks"] = 100     # here is the copy chages not made in original data set

print(new_df)
print(df)    #---- no changes after the modification in copy

   marks
0    100
1    100
   marks
0     80
1     90
2     70

#### in summery best use to use .copy in every modification of real dataset

In [165]:
import pandas as pd
data = {
    "Name" : ["soumya", "rahul",  "aman"],
    "age" : [21,23,22]
}

df = pd.DataFrame(data)
print(df)

     Name  age
0  soumya   21
1   rahul   23
2    aman   22

In [32]:
import pandas as pd
df = pd.read_csv("data\globalAirQuality.csv")
data = df["aqi"]>100  #---- if we select that then it will be give the true and false values if the condition is true
data=df[df["aqi"]>100]
# print(data)


# temp >30 and aqi>100 select on both condition
# df[(df["aqi"]>100) & (df["temperature"]>30)] 


aqi_data = df[(df["aqi"]>100) & (df["temperature"]>30)] [["city", "aqi"]]

# print(aqi_data.iloc[0])

aqi_data.iloc[0]
# aqi_data.loc[0]   # ------ IT GIVES ERROR BECAUSE THE .loc FUNCTION DO NOT OPERATE ON INDEX VALUES IT OPERTES ON LABELD VALUE OF THE LEBLE 0 IS NOT PRESENT AND WE TRY TO PRINT THAT THEN THAT WILLBE GIVE AN ERROR

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Asus\AppData\Local\Temp\ipykernel_22616\3781730290.py:2: SyntaxWarning: invalid escape sequence '\g'
  df = pd.read_csv("data\globalAirQuality.csv")

city    New York
aqi          155
Name: 6, dtype: object

In [ ]:
marks = pd.Series(
    [80,"shark",70],
    index=["A","B","C"]
)

# print(marks.values)
# print(marks.index)
# print(marks.dtype)
# marks.describe()
# marks.info()

count      3
unique     3
top       80
freq       1
dtype: int64

In [57]:
marks = pd.DataFrame(
    [80,"shark",70],
    index=["A","B","C"]
)
print(marks)


marks[1] =[20,100,234]
# marks = marks.drop(1,axis = 0)
marks.values

       0
A     80
B  shark
C     70

array([[80, 20],
       ['shark', 100],
       [70, 234]], dtype=object)

In [17]:
import pandas as pd
data = {
    "name": ["soumya", "rahul", "aman"],
    "age" : [21,20,19]
}
df = pd.DataFrame(data)
df["branch"] = ["cs","cse","mech"]                 # all operations are performed in the copy noty in the real part 
df.drop(0,axis = 0)
df.drop("branch",axis = 1)

     name  age
0  soumya   21
1   rahul   20
2    aman   19

In [ ]:
import pandas as pd

data = pd.read_csv("data\missingData.csv")
data.isnull()  #-,
data.isna()    #-   both are same functional work which generate the null or missing values with boolean function

data.isnull().sum()  # -----basically chainign and statisticall summery persorm in the single function gives the sum of the null values as in the entire columns
data.isna().sum()  # same as upper 

# data.dropna()  # --- basically delete the entire row which contain the missing values


# data.fillna(0) # --- fill the values inplace of null or missing values

# data.ffil() # forward fill vslues if 1 is teh value in the 1st row of column age and null is in the 2nd rows column age then after the forward fill the 1 should be copied and filled in the nul value of the 2nd row 
data.bfill()

# data   # FOR CHECKING THE VALUE which is changed or not

<>:3: SyntaxWarning: invalid escape sequence '\m'
<>:3: SyntaxWarning: invalid escape sequence '\m'
C:\Users\Asus\AppData\Local\Temp\ipykernel_13896\599593878.py:3: SyntaxWarning: invalid escape sequence '\m'
  data = pd.read_csv("data\missingData.csv")

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### Pandas part2 Feat Engg

In [ ]:
import pandas as pd

df = pd.read_csv("data\example.csv")

# apply()
df["tax"] = df["income"].apply(lambda x : "20%" if x>=60000 else "10%" )


# map()
new_gender = {
    "Male" : "M",
    "Female" : "F",
    "Unknown" : "U"
}
df["gender"] = df["gender"].map(new_gender)


# apply()
# new_df = df.assign(column_name1=value1, column_name2=value2, ...)     syntax
# This works because lambda x sees the newly added 'tax' column
df = df.assign(
    tax = df["income"] * 1.1, 
    rate = lambda x: x["tax"] / 10000
)


# replace()
# Replaces 1 with 'A', and 2 with 'B'
# df = df.replace([1, 2], ['A', 'B'])
# # Clean mapping syntax
# df = df.replace({1: 'A', 2: 'B'})
# # Only replaces values inside the 'status' column
# df = df.replace({'status': {'pending': 'hold', 'complete': 'active'}})

df["country"] = df["country"].replace(["USA","Canada","Spain","China","India","Mexico"], ["US", "Ca", "Spn", "Ch", "Ind","Mex"])
df

<>:3: SyntaxWarning: invalid escape sequence '\e'
<>:3: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Asus\AppData\Local\Temp\ipykernel_7356\2014598341.py:3: SyntaxWarning: invalid escape sequence '\e'
  df = pd.read_csv("data\example.csv")

    id          name   age country gender   income      tax  rate
0    1      John Doe  29.0      US      M  55000.0  60500.0  6.05
1    1      John Doe  29.0      US      M  55000.0  60500.0  6.05
2    2    Jane Smith   NaN      Ca      F  62000.0  68200.0  6.82
3    3          Alex   NaN      US      U  47000.0  51700.0  5.17
4    4  Maria Garcia  34.0     Spn      F      NaN      NaN   NaN
5    5        Li Wei  27.0      Ch      M  51000.0  56100.0  5.61
6    6           NaN  45.0     Ind      F  73000.0  80300.0  8.03
7    7    Ahmed Khan  38.0     NaN      M  68000.0  74800.0  7.48
8    8    Rachel Lee  29.0      US      F  62000.0  68200.0  6.82
9    9   Carlos Ruiz   NaN     Mex      M  45000.0  49500.0  4.95
10  10   Emily Davis  31.0      US    NaN  58000.0  63800.0  6.38

In [13]:
# renaming / reordering
dataf = pd.DataFrame({
"A": [1, 2, 3],
"B": [4, 5, 6],
"C": [7, 8, 9]
})
df3 = dataf.rename(columns={
    "A":"X",
    "B":"Y"
})
print(df3)

   X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
df.columns = [["name","age","country","gender","incoome","tax","rate","id"]]   # this basically change the names not the order of columns

df.rename(columns={
    "name":"Name",
    "id": "ID"
})           # this is another kind of renaming a specific column


df.columns = [["id","Name","age","Country","gender","income","tax","rate"]]

In [34]:
df.rename(columns={
    "income": "salary"
})

    id          Name   age Country gender   salary      tax  rate
0    1      John Doe  29.0      US      M  55000.0  60500.0  6.05
1    1      John Doe  29.0      US      M  55000.0  60500.0  6.05
2    2    Jane Smith   NaN      Ca      F  62000.0  68200.0  6.82
3    3          Alex   NaN      US      U  47000.0  51700.0  5.17
4    4  Maria Garcia  34.0     Spn      F      NaN      NaN   NaN
5    5        Li Wei  27.0      Ch      M  51000.0  56100.0  5.61
6    6           NaN  45.0     Ind      F  73000.0  80300.0  8.03
7    7    Ahmed Khan  38.0     NaN      M  68000.0  74800.0  7.48
8    8    Rachel Lee  29.0      US      F  62000.0  68200.0  6.82
9    9   Carlos Ruiz   NaN     Mex      M  45000.0  49500.0  4.95
10  10   Emily Davis  31.0      US    NaN  58000.0  63800.0  6.38

In [ ]:
df2 = df.copy()
df2.rename(index={1:"First"})

       id          Name   age Country gender   income      tax  rate
0       1      John Doe  29.0      US      M  55000.0  60500.0  6.05
First   1      John Doe  29.0      US      M  55000.0  60500.0  6.05
2       2    Jane Smith   NaN      Ca      F  62000.0  68200.0  6.82
3       3          Alex   NaN      US      U  47000.0  51700.0  5.17
4       4  Maria Garcia  34.0     Spn      F      NaN      NaN   NaN
5       5        Li Wei  27.0      Ch      M  51000.0  56100.0  5.61
6       6           NaN  45.0     Ind      F  73000.0  80300.0  8.03
7       7    Ahmed Khan  38.0     NaN      M  68000.0  74800.0  7.48
8       8    Rachel Lee  29.0      US      F  62000.0  68200.0  6.82
9       9   Carlos Ruiz   NaN     Mex      M  45000.0  49500.0  4.95
10     10   Emily Davis  31.0      US    NaN  58000.0  63800.0  6.38

#### sort_values() sort_index() reset_index()

In [68]:
import pandas as pd
df = pd.read_csv("data\example.csv")
df = df.drop_duplicates()

<>:2: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Asus\AppData\Local\Temp\ipykernel_14636\239877756.py:2: SyntaxWarning: invalid escape sequence '\e'
  df = pd.read_csv("data\example.csv")

In [69]:
# sort
sorted_df = df.sort_values("income", ascending=False)

# index sorting  
sorted_df.sort_index()
sorted_df.reset_index()
sorted_df.reset_index(drop=True) # to drop original index vals

   id          name   age country   gender   income
0   6           NaN  45.0   India   Female  73000.0
1   7    Ahmed Khan  38.0     NaN     Male  68000.0
2   8    Rachel Lee  29.0     USA   Female  62000.0
3   2    Jane Smith   NaN  Canada   Female  62000.0
4  10   Emily Davis  31.0     USA      NaN  58000.0
5   1      John Doe  29.0     USA     Male  55000.0
6   5        Li Wei  27.0   China     Male  51000.0
7   3          Alex   NaN     USA  Unknown  47000.0
8   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
9   4  Maria Garcia  34.0   Spain   Female      NaN

In [70]:
df.sort_values("income")
df.sort_index()
df.reset_index(drop=True)
df.fillna("----")

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  ----  Canada   Female  62000.0
3    3          Alex  ----     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female     ----
5    5        Li Wei  27.0   China     Male  51000.0
6    6          ----  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0    ----     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  ----  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     ----  58000.0

In [ ]:
sorted_df["ranking"] = sorted_df["income"].rank()
sorted_df
# df.sort_values("income")

hist ( ) is not working

In [ ]:
df["ranking"] = df["income"].rank()
df.hist()

In [15]:
import pandas as pd
data = pd.read_csv("data\example.csv")
df2 = data.copy()                  # MAKES COPY SO THAT THE CHANGES NOT REFLECT ON THE REAL DATASET
df2=df2.sort_values("income")         # sort the values based on income and the labels are get random 
df2 = df2.reset_index(drop = True)   # reset index lebels bsaed on changes  ( drop = true removes the previous unsorted index completely)
df2["rank"] = df2["income"].rank(ascending=False, method="dense" )   # ( rank the income on the basis from descending ---> represented by ascending = false )
   # "dense" makes the complete integer of the decemal value like remove .s 

# df2["rank"].rank(method="min")
df2

<>:2: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Asus\AppData\Local\Temp\ipykernel_3212\624493367.py:2: SyntaxWarning: invalid escape sequence '\e'
  data = pd.read_csv("data\example.csv")

    id          name   age country   gender   income  rank
0    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   8.0
1    3          Alex   NaN     USA  Unknown  47000.0   7.0
2    5        Li Wei  27.0   China     Male  51000.0   6.0
3    1      John Doe  29.0     USA     Male  55000.0   5.0
4    1      John Doe  29.0     USA     Male  55000.0   5.0
5   10   Emily Davis  31.0     USA      NaN  58000.0   4.0
6    2    Jane Smith   NaN  Canada   Female  62000.0   3.0
7    8    Rachel Lee  29.0     USA   Female  62000.0   3.0
8    7    Ahmed Khan  38.0     NaN     Male  68000.0   2.0
9    6           NaN  45.0   India   Female  73000.0   1.0
10   4  Maria Garcia  34.0   Spain   Female      NaN   NaN

In [18]:
df = df2.copy()
df["rank"].rank(method="min")
df

    id          name   age country   gender   income  rank
0    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   8.0
1    3          Alex   NaN     USA  Unknown  47000.0   7.0
2    5        Li Wei  27.0   China     Male  51000.0   6.0
3    1      John Doe  29.0     USA     Male  55000.0   5.0
4    1      John Doe  29.0     USA     Male  55000.0   5.0
5   10   Emily Davis  31.0     USA      NaN  58000.0   4.0
6    2    Jane Smith   NaN  Canada   Female  62000.0   3.0
7    8    Rachel Lee  29.0     USA   Female  62000.0   3.0
8    7    Ahmed Khan  38.0     NaN     Male  68000.0   2.0
9    6           NaN  45.0   India   Female  73000.0   1.0
10   4  Maria Garcia  34.0   Spain   Female      NaN   NaN

#### Writing to a csv

In [24]:
df.fillna("---")
df.to_csv("data\changed.csv")
df.to_json("data\changed.json")
# f.to_json("data\changed.")

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:3: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:3: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Asus\AppData\Local\Temp\ipykernel_3212\2613219207.py:2: SyntaxWarning: invalid escape sequence '\c'
  df.to_csv("data\changed.csv")
C:\Users\Asus\AppData\Local\Temp\ipykernel_3212\2613219207.py:3: SyntaxWarning: invalid escape sequence '\c'
  df.to_json("data\changed.json")

#### Grouping and aggregation

In [53]:
# data
data[["country","income"]]
min = data.groupby("country")["income"].min()   # finding min

mean = data.groupby("country")["income"].mean()
print(mean)

# using aggregate function or agg()

aggr = data.groupby("country")["income"].agg(["min","sum","mean","max"])
print(aggr)

agg2 = data.groupby("country").agg({
        "income" : "min",
        "age":"max"
})

agg3 = data.groupby("country").agg(
    avg_val = ("income","mean"),
    avg_age = ("age" , "mean")
    )

agg3

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64
             min       sum     mean      max
country
Canada   62000.0   62000.0  62000.0  62000.0
China    51000.0   51000.0  51000.0  51000.0
India    73000.0   73000.0  73000.0  73000.0
Mexico   45000.0   45000.0  45000.0  45000.0
Spain        NaN       0.0      NaN      NaN
USA      47000.0  277000.0  55400.0  62000.0

         avg_val  avg_age
country
Canada   62000.0      NaN
China    51000.0     27.0
India    73000.0     45.0
Mexico   45000.0      NaN
Spain        NaN     34.0
USA      55400.0     29.5

#### Melt and pivot

In [60]:
import pandas as pd

# Sample data: Sales revenue per product for Q1 and Q2
data = {
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Category': ['Electronics', 'Electronics', 'Tech'],
    'Q1_Sales': [12000, 4500, 8000],
    'Q2_Sales': [15000, 5000, 9500]
}

df = pd.DataFrame(data)
# print("Original Wide DataFrame:")
# print(df)

df_long = df.melt(                                     # melting
    id_vars=["Product","Category"],
    value_vars=["Q1_Sales", "Q2_Sales"],
    var_name="Quarter_Sale",
    value_name="Revenue"
)



# pivot
df_short = df_long.pivot(
    index = ["Product","Category"],
    columns = "Quarter_Sale",
    values = "Revenue"
)

print(df_short)

Quarter_Sale         Q1_Sales  Q2_Sales
Product Category
Laptop  Electronics     12000     15000
Phone   Tech             8000      9500
Tablet  Electronics      4500      5000

# Pandas part one revise

In [2]:
import pandas as pd
data = pd.read_json("data\stu_perf.json")


data.shape    # (row , col)

type(data)     # kind of data

data.columns     # print the columns name
data.dtypes       # data types of columns

# basic operations

data.head()           # give first 5 data 

data.tail(7)             # give last 5 data  (nums of data) we add inside the tail function

data.info()               # summery likr non-null dtypes columns

data.describe()             # aggrigation functions like ( mean, median, min, max )

data.sample()               # giving a random data the entire row as sample


# data.index("")    # this works on the series 

data.size         #130   total datas row x columns

data.ndim                # 2 bcz its a data frame

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Asus\AppData\Local\Temp\ipykernel_16088\2799660483.py:2: SyntaxWarning: invalid escape sequence '\s'
  data = pd.read_json("data\stu_perf.json")

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          10 non-null     int64
 1   name                10 non-null     str
 2   gender              10 non-null     str
 3   branch              10 non-null     str
 4   semester            10 non-null     int64
 5   city                9 non-null      str
 6   attendance          9 non-null      float64
 7   python_marks        9 non-null      float64
 8   dbms_marks          10 non-null     int64
 9   os_marks            10 non-null     int64
 10  placement_training  10 non-null     str
 11  fee_status          10 non-null     str
 12  exam_date           10 non-null     str
dtypes: float64(2), int64(4), str(7)
memory usage: 1.1 KB

2

In [ ]:
# selection and indexing

data.iloc[0:4]      # inclusive
data.loc[0:4]       # exclusive  
data.at[0,"city"]        # for a particular cell
data.iat[0,5]            # only index based

'Bhubaneswar'

In [17]:
# Filtering and function

cities = ["Bhubaneswar", "Cuttuck","Rourkela"]
data["city"].isin(cities)


# data.mask(cond, other=NaN, inplace=False)   # whenever some value is set based on condition to the entire dataq set   this is used
data["semester"] = data["semester"].mask(data["semester"] == 5,"odd sem")

In [ ]:
# missing values functons
data.isnull()
data["city"].isnull()
data["city"].notnull()
data["city"].fillna("Null")
# data.dropna()      # delete entire row which contain Nan
data["city"].dropna()
data.ffill()  # forward fill
data.bfill()  #backword fill

,student_id,name,gender,branch,semester,city,attendance,python_marks,dbms_marks,os_marks,placement_training,fee_status,exam_date
0,101,Soumya,Male,CSE,odd sem,Bhubaneswar,85.0,92.0,88,90,Yes,Paid,2025-12-10
1,102,Rahul,Male,ECE,odd sem,Cuttack,70.0,75.0,68,72,No,Paid,2025-12-11
2,103,Priya,Female,CSE,odd sem,Rourkela,60.0,95.0,91,94,Yes,Pending,2025-12-12
3,104,Aman,Male,ME,odd sem,Bhubaneswar,60.0,55.0,58,62,No,Paid,2025-12-13
4,105,Sneha,Female,ECE,odd sem,Bhubaneswar,90.0,88.0,84,89,Yes,Paid,2025-12-14
5,106,Karan,Male,Civil,odd sem,Angul,45.0,40.0,42,38,No,Pending,2025-12-15
6,107,Anjali,Female,CSE,6,Sambalpur,95.0,98.0,97,96,Yes,Paid,2026-01-10
7,108,Rohit,Male,ECE,6,Balasore,80.0,82.0,75,77,Yes,Paid,2026-01-11
8,109,Pooja,Female,ME,6,Cuttack,78.0,82.0,80,84,No,Paid,2026-01-12
9,109,Pooja,Female,ME,6,Cuttack,78.0,82.0,80,84,No,Paid,2026-01-12

In [ ]:
# de duplication
#finding duplicates
data["city"].duplicated()

data = data.drop_duplicates()           # works on entire data

In [43]:
data

,student_id,name,gender,branch,semester,city,attendance,python_marks,dbms_marks,os_marks,placement_training,fee_status,exam_date
0,101,Soumya,Male,CSE,odd sem,Bhubaneswar,85.0,92.0,88,90,Yes,Paid,2025-12-10
1,102,Rahul,Male,ECE,odd sem,Cuttack,70.0,75.0,68,72,No,Paid,2025-12-11
2,103,Priya,Female,CSE,odd sem,Rourkela,NaN,95.0,91,94,Yes,Pending,2025-12-12
3,104,Aman,Male,ME,odd sem,NaN,60.0,55.0,58,62,No,Paid,2025-12-13
4,105,Sneha,Female,ECE,odd sem,NaN,90.0,88.0,84,89,Yes,Paid,2025-12-14
5,106,Karan,Male,Civil,odd sem,Angul,45.0,40.0,42,38,No,Pending,2025-12-15
6,107,Anjali,Female,CSE,6,Sambalpur,95.0,98.0,97,96,Yes,Paid,2026-01-10
7,108,Rohit,Male,ECE,6,Balasore,80.0,NaN,75,77,Yes,Paid,2026-01-11
8,109,Pooja,Female,ME,6,NaN,78.0,82.0,80,84,No,Paid,2026-01-12

RangeIndex(start=0, stop=10, step=1)